sources.cmake
test_app_glance.c
test_app_inbox.c
test_app_message.c
test_app_outbox.c
test_app_smartstrap.c
test_bitmap_layer.c
test_cpu_cache.c
test_pbl_std.c
test_persist.c
test_template_string.c
test_text_render.c
test_text_resources.c
test_unobstructed_area_service.c
